*&---------------------------------------------------------------------*
*&  Include           ZXVVFU04
*&---------------------------------------------------------------------*
TABLES: VBFA, VBAK.

DATA: ZZVBRK   LIKE VBRK,
*     ZZVBRP   LIKE XVBRP,
      ZZXACCIT LIKE XACCIT,
      ZZXVBRP  LIKE XVBRP.

ZZVBRK   = VBRK.
*ZZVBRP   = XVBRP.
ZZXACCIT = XACCIT.
ZZXVBRP  = XVBRP.
ZZXACCIT-MATNR = ZZXVBRP-MATNR.

*ZZVBRP-FKIMG   = ZZXACCIT-MENGE.
*ZZVBRP-VRKME   = ZZXACCIT-MEINS.

IF ZZVBRK-VKORG = 'Z001'.
   ZZXACCIT-SGTXT = 'BANNER GAS SALES'.

ELSEIF ZZVBRK-VKORG = 'Z002'.
   ZZXACCIT-ZUONR = ZZVBRK-ZUONR.
   ZZXACCIT-XBLNR = ZZVBRK-XBLNR.
   IF ZZVBRK-XBLNR = 'ZAC'.
      CONCATENATE ZZVBRK-KUNAG TEXT-101 INTO ZZXACCIT-SGTXT.
   ELSEIF ZZVBRK-ZUONR = 'ZES'.
      CONCATENATE ZZVBRK-KUNAG TEXT-102 INTO ZZXACCIT-SGTXT.
   ELSEIF ZZVBRK-ZUONR = 'ZRV'.
      CONCATENATE ZZVBRK-KUNAG TEXT-103 INTO ZZXACCIT-SGTXT.
   ENDIF.

ELSEIF ZZVBRK-VKORG = 'Z003'.
   ZZXACCIT-ZUONR = ZZVBRK-ZUONR.
   ZZXACCIT-XBLNR = ZZVBRK-XBLNR.
   IF ZZVBRK-XBLNR = 'ZAC'.
      CONCATENATE ZZVBRK-KUNAG TEXT-104 INTO ZZXACCIT-SGTXT.
   ELSEIF ZZVBRK-ZUONR = 'ZES'.
      CONCATENATE ZZVBRK-KUNAG TEXT-105 INTO ZZXACCIT-SGTXT.
   ELSEIF ZZVBRK-ZUONR = 'ZRV'.
      CONCATENATE ZZVBRK-KUNAG TEXT-106 INTO ZZXACCIT-SGTXT.
   ENDIF.
ENDIF.
"--------SAHMAD - CHG0225506 that will refer to Normal Change Request CHG0223869
data: lv_assign type ZLSD_PGIDATE-ASSIGNMENT_FI,
      lv_kunnr   TYPE vbrk-KUNAG.

lv_kunnr = '*'.

SELECT SINGLE ASSIGNMENT_FI INTO lv_assign
  FROM ZLSD_PGIDATE
  WHERE vkorg = vbrk-vkorg
    AND kunnr = vbrk-KUNAG.

IF sy-subrc <> 0.
SELECT SINGLE ASSIGNMENT_FI INTO lv_assign
  FROM ZLSD_PGIDATE
  WHERE vkorg = vbrk-vkorg
    AND kunnr = lv_kunnr.
ENDIF.
IF lv_assign IS NOT INITIAL.
   XACCIT-zuonr = vbrk-zuonr.
   XACCIT-kunnr = vbrk-kunag. " COG
ENDIF.
